baseURL = '/'
languageCode = 'en-us'
title = 'Andrew M McCall'
theme = 'megalawnalien'
paginate = 10

[markup.goldmark.renderer]
unsafe = true

[params]
 description = "Andrew M McCall is a fullstack web developer in Traverse City, Michigan who loves Go, Lua, PHP, Javascript, Vanilla CSS, SQL, Postgresql, Semantic HTML, and Accessibility."
 social = [
    { name = "mastodon", url = "https://indieweb.social/@elkcityhazard" },
    { name = "github", url = "https://github.com/elkcityhazard" },
    { name = "gitlab", url = "https://gitlab.com/elkcityhazard" },
    { name = "linkedIn", url = "https://www.linkedin.com/in/andrew-mccall-8a09582b3/" }
 ]

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20


[[menus.main]]
name = 'Resume'
pageRef = '/resume'
weight = 30


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

