baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Andrew M McCall'
name = "megalawnalien"

[params]
description = "Andrew M McCall is a fullstack web developer with 6 years of professional experience in Golang, Javascript, PHP, Lua, MongoDB, Mysql, Postgres, and NGINX, & Caddy"

[markup.goldmark.renderer]
unsafe = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Resume'
pageRef = '/resume'
weight = 40


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
