######################## default configuration ####################
baseURL = "https://www.andrew-mccall.com/"
theme = "somrat"
title = "Andrew McCall - Fullstack Web Developer - Traverse City, Michigan"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = true
# google analutics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# publish directory

############################# Outputs ##############################
[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
#[[params.plugins.css.blank]]
#link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
#[[params.plugins.css.blank]]
#link = "https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"


[[params.plugins.localcss]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.localcss]]
link = "plugins/hover/hover.css"
[[params.plugins.localcss]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.localcss]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.localcss]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.localcss]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.localcss]]
link = "css/style.css"
[[params.plugins.localcss]]
link = "css/custom.css" 


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"

#################### default parameters ################################
[params]
favicon = "images/favicon-transparent.ico"
logo_dark = "images/svg/logo-black.svg"
logo_light = "images/logo-white.png"
logo_width = "150px"
# Meta data
author = "andrew mccall"
description = "I believe in a less complicated digital experience for my clients.   Andrew McCall is a fullstack web developer based in Traverse City, Michigan."
images = ["/images/social/twitter/share.png"]

# Preloader
[params.preloader]
enable = true 
preloader = "/images/svg/logo-small-transparent.svg" # use jpg, png, svg or gif format.

############RSS FEED##############

copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
languageCode = 'en-us'
[author]
  name = 'Andrew M McCall'



########################### Physical Address #####################
[params.address]
address = "4889 Silver Pines Rd"
city = "Traverse City, Michigan <br /> 49685"
name = "Andrew M McCall"
phone = "12312990217"

############################# social site ########################
[[params.social]]
icon = "fab fa-facebook-f"
link = "https://www.facebook.com/andrew.mccall.18062"

[[params.social]]
icon = "fab fa-twitter"
link = "https://twitter.com/elkcityhazard"

[[params.social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/elkcityhazard"

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/elkcityhazard"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/elkcityhazard"

[[params.social]]
icon = "fab fa-mastodon"
link = "https://indieweb.social/@elkcityhazard" 

################################### English language #####################################
[Languages.en]
contentDir = "content/"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
# copyright
copyright = "Copyright &copy; 2021  [andrew mccall](https://andrew-mccall.com)"

################# english navigation ##################

# main menu

[[Languages.en.menu.main]]
name = "About Andrew"
url = "/about"
weight = 2

[[Languages.en.menu.main]]
name = "Internet Marketing Services"
pre = ""
url = "/services"
weight = 3

[[Languages.en.menu.main]]
name = "Portfolio"
pre = "#"
url = "/portfolio"
weight = 4

[[Languages.en.menu.main]]
name = "Testimonial"
pre = "#"
url = "/testimonial"
weight = 5

[[Languages.en.menu.main]]
name = "Contact"
pre = "#"
url = "/contact"
weight = 6

[[Languages.en.menu.main]]
name = "Blog"
url = "/blog"
weight = 7

#######Services Submenu###########

[[Languages.en.menu.services]]
name = "Web Development"
parent = "services"
url = "services/web-development-traverse-city"
weight = 1

[[Languages.en.menu.services]]
name = "Content Marketing"
parent = "services"
url = "services/traverse-city-content-marketing"
weight = 1

